// examples/vue/useHotkeySequenceRecorder/src/ShortcutListItem.vue
<script setup lang="ts">
import { formatForDisplay, useHeldKeys } from '@tanstack/vue-hotkeys'
import type { HotkeySequence } from '@tanstack/vue-hotkeys'

interface Shortcut {
  id: string
  name: string
  description: string
  sequence: HotkeySequence
}

defineProps<{
  shortcut: Shortcut
  isEditing: boolean
  draftName: string
  draftDescription: string
  liveSteps: HotkeySequence
}>()

defineEmits<{
  'update:draftName': [value: string]
  'update:draftDescription': [value: string]
  edit: []
  save: []
  cancel: []
  delete: []
}>()

const heldKeys = useHeldKeys()

function formatSeq(seq: HotkeySequence): string {
  return seq.map((h) => formatForDisplay(h)).join(' ')
}
</script>

<template>
  <div class="shortcut-item" :class="{ recording: isEditing }">
    <div class="shortcut-item-content">
      <div class="shortcut-action">
        <template v-if="isEditing">
          <div class="editing-fields">
            <input
              type="text"
              class="edit-input edit-name"
              :value="draftName"
              placeholder="Shortcut name"
              @input="
                $emit(
                  'update:draftName',
                  ($event.target as HTMLInputElement).value,
                )
              "
            />
            <input
              type="text"
              class="edit-input edit-description"
              :value="draftDescription"
              placeholder="Description (optional)"
              @input="
                $emit(
                  'update:draftDescription',
                  ($event.target as HTMLInputElement).value,
                )
              "
            />
          </div>
        </template>
        <template v-else>
          <template v-if="shortcut.name">{{ shortcut.name }}</template>
          <span v-else class="unnamed">Unnamed</span>
          <div v-if="shortcut.description" class="shortcut-description">
            {{ shortcut.description }}
          </div>
        </template>
      </div>
      <div class="shortcut-hotkey">
        <div v-if="isEditing" class="recording-indicator">
          <span v-if="liveSteps.length > 0" class="held-hotkeys">{{
            formatSeq(liveSteps)
          }}</span>
          <div v-else-if="heldKeys.length > 0" class="held-hotkeys">
            <template v-for="(key, index) in heldKeys" :key="key">
              <span v-if="index > 0" class="plus">+</span>
              <kbd>{{ key }}</kbd>
            </template>
          </div>
          <span v-else class="recording-text">Press chords, then Enter...</span>
        </div>
        <kbd v-else-if="shortcut.sequence.length > 0">{{
          formatSeq(shortcut.sequence)
        }}</kbd>
        <span v-else class="no-shortcut">No shortcut</span>
      </div>
    </div>
    <div class="shortcut-actions">
      <template v-if="isEditing">
        <button type="button" class="save-button" @click="$emit('save')">
          Save
        </button>
        <button type="button" class="cancel-button" @click="$emit('cancel')">
          Cancel
        </button>
      </template>
      <template v-else>
        <button type="button" class="edit-button" @click="$emit('edit')">
          Edit
        </button>
        <button type="button" class="delete-button" @click="$emit('delete')">
          Delete
        </button>
      </template>
    </div>
  </div>
</template>

// examples/svelte/create-hotkey-sequence-recorder/src/ShortcutListItem.svelte
<script lang="ts">
  import { formatForDisplay, getHeldKeys } from '@tanstack/svelte-hotkeys'
  import type { HotkeySequence } from '@tanstack/svelte-hotkeys'

  interface Shortcut {
    id: string
    name: string
    description: string
    sequence: HotkeySequence
  }

  interface Props {
    shortcut: Shortcut
    isEditing: boolean
    draftName: string
    draftDescription: string
    onDraftNameChange: (value: string) => void
    onDraftDescriptionChange: (value: string) => void
    liveSteps: HotkeySequence
    onEdit: () => void
    onSave: () => void
    onCancel: () => void
    onDelete: () => void
  }

  let {
    shortcut,
    isEditing,
    draftName,
    draftDescription,
    onDraftNameChange,
    onDraftDescriptionChange,
    liveSteps,
    onEdit,
    onSave,
    onCancel,
    onDelete,
  }: Props = $props()

  const heldKeys = getHeldKeys()

  function formatSeq(seq: HotkeySequence): string {
    return seq.map((h) => formatForDisplay(h)).join(' ')
  }
</script>

<div class="shortcut-item" class:recording={isEditing}>
  <div class="shortcut-item-content">
    <div class="shortcut-action">
      {#if isEditing}
        <div class="editing-fields">
          <input
            type="text"
            class="edit-input edit-name"
            value={draftName}
            oninput={(e) => onDraftNameChange(e.currentTarget.value)}
            placeholder="Shortcut name"
          />
          <input
            type="text"
            class="edit-input edit-description"
            value={draftDescription}
            oninput={(e) => onDraftDescriptionChange(e.currentTarget.value)}
            placeholder="Description (optional)"
          />
        </div>
      {:else}
        {#if shortcut.name}
          {shortcut.name}
        {:else}
          <span class="unnamed">Unnamed</span>
        {/if}
        {#if shortcut.description}
          <div class="shortcut-description">{shortcut.description}</div>
        {/if}
      {/if}
    </div>
    <div class="shortcut-hotkey">
      {#if isEditing}
        <div class="recording-indicator">
          {#if liveSteps.length > 0}
            <span class="held-hotkeys">{formatSeq(liveSteps)}</span>
          {:else if heldKeys.keys.length > 0}
            <div class="held-hotkeys">
              {#each heldKeys.keys as key, index}
                {#if index > 0}
                  <span class="plus">+</span>
                {/if}
                <kbd>{key}</kbd>
              {/each}
            </div>
          {:else}
            <span class="recording-text">Press chords, then Enter...</span>
          {/if}
        </div>
      {:else if shortcut.sequence.length > 0}
        <kbd>{formatSeq(shortcut.sequence)}</kbd>
      {:else}
        <span class="no-shortcut">No shortcut</span>
      {/if}
    </div>
  </div>
  <div class="shortcut-actions">
    {#if isEditing}
      <button type="button" onclick={onSave} class="save-button">Save</button>
      <button type="button" onclick={onCancel} class="cancel-button">
        Cancel
      </button>
    {:else}
      <button type="button" onclick={onEdit} class="edit-button">Edit</button>
      <button type="button" onclick={onDelete} class="delete-button">
        Delete
      </button>
    {/if}
  </div>
</div>
