// examples/vue/kitchen-sink/src/EditorPane.vue
<script setup lang="ts">
import { inject, ref } from 'vue'
import { formatForDisplay, useHotkeys } from '@tanstack/vue-hotkeys'

const props = defineProps<{ name: string }>()
const log = inject<(message: string) => void>('log')!
const target = ref<HTMLElement | null>(null),
  text = ref('One shortcut, two independent editors.'),
  saves = ref(0)
useHotkeys(
  [
    {
      hotkey: 'Mod+[KeyS]',
      callback: () => {
        saves.value++
        log(`${props.name} saved`)
      },
      options: { meta: { name: `Save ${props.name}`, group: 'Editor' } },
    },
    {
      hotkey: 'Alt+[Backspace]',
      callback: () => {
        text.value = ''
      },
      options: { meta: { name: `Clear ${props.name}`, group: 'Editor' } },
    },
  ],
  { target, ignoreInputs: false },
)
</script>
<template>
  <fieldset ref="target">
    <legend>{{ name }} — {{ saves }} saves</legend>
    <label>Editor content<textarea v-model="text" rows="3" /></label>
    <p>
      <kbd>{{ formatForDisplay('Mod+[KeyS]') }}</kbd> Save;
      <kbd>{{ formatForDisplay('Alt+[Backspace]') }}</kbd> Clear
    </p>
  </fieldset>
</template>

// examples/svelte/kitchen-sink/src/EditorPane.svelte
<script lang="ts">
  import { getContext } from 'svelte'
  import {
    createHotkeysAttachment,
    formatForDisplay,
  } from '@tanstack/svelte-hotkeys'
  let { name }: { name: string } = $props()
  const log = getContext<(message: string) => void>('log')
  let text = $state('One shortcut, two independent editors.'),
    saves = $state(0)
  const shortcuts = createHotkeysAttachment(
    () => [
      {
        hotkey: 'Mod+[KeyS]',
        callback: () => {
          saves++
          log(`${name} saved`)
        },
        options: { meta: { name: `Save ${name}`, group: 'Editor' } },
      },
      {
        hotkey: 'Alt+[Backspace]',
        callback: () => {
          text = ''
        },
        options: { meta: { name: `Clear ${name}`, group: 'Editor' } },
      },
    ],
    { ignoreInputs: false },
  )
</script>

<fieldset {@attach shortcuts}>
  <legend>{name} — {saves} saves</legend><label
    >Editor content<textarea rows="3" bind:value={text}></textarea></label
  >
  <p>
    <kbd>{formatForDisplay('Mod+[KeyS]')}</kbd> Save;
    <kbd>{formatForDisplay('Alt+[Backspace]')}</kbd> Clear
  </p>
</fieldset>
