// examples/angular/injectHotkeyRecorder/src/app/app.component.ts
import { Component, signal } from '@angular/core'
import {
  formatForDisplay,
  injectHeldKeys,
  injectHotkeyRecorder,
  injectHotkeyRegistrations,
  injectHotkeys,
} from '@tanstack/angular-hotkeys'
import type { Hotkey, InjectHotkeyDefinition } from '@tanstack/angular-hotkeys'

interface Shortcut {
  id: string
  name: string
  description: string
  hotkey: Hotkey | ''
}

let nextId = 0
function createId(): string {
  return `shortcut_${++nextId}`
}

const INITIAL_SHORTCUTS: Array<Shortcut> = [
  {
    id: createId(),
    name: 'Save',
    description: 'Save the current document',
    hotkey: 'Mod+K',
  },
  {
    id: createId(),
    name: 'Open',
    description: 'Open a file from disk',
    hotkey: 'Mod+E',
  },
  {
    id: createId(),
    name: 'New',
    description: 'Create a new document',
    hotkey: 'Mod+G',
  },
  {
    id: createId(),
    name: 'Close',
    description: 'Close the current tab',
    hotkey: 'Mod+Shift+K',
  },
  {
    id: createId(),
    name: 'Undo',
    description: 'Undo the last action',
    hotkey: 'Mod+Shift+E',
  },
  {
    id: createId(),
    name: 'Redo',
    description: 'Redo the last undone action',
    hotkey: 'Mod+Shift+G',
  },
]

@Component({
  selector: 'app-root',
  standalone: true,
  templateUrl: './app.component.html',
  styleUrl: './app.component.css',
})
export class AppComponent {
  shortcuts = signal<Array<Shortcut>>(INITIAL_SHORTCUTS)
  editingId = signal<string | null>(null)
  draftName = signal('')
  draftDescription = signal('')

  formatForDisplay = formatForDisplay
  heldKeys = injectHeldKeys()

  private readonly recorder = injectHotkeyRecorder({
    onRecord: (hotkey: Hotkey) => {
      const id = this.editingId()
      if (id) {
        this.shortcuts.update((prev) =>
          prev.map((s) =>
            s.id === id
              ? {
                  ...s,
                  hotkey,
                  name: this.draftName(),
                  description: this.draftDescription(),
                }
              : s,
          ),
        )
        this.editingId.set(null)
      }
    },
    onCancel: () => {
      const id = this.editingId()
      if (id) {
        this.shortcuts.update((prev) => {
          const shortcut = prev.find((s) => s.id === id)
          if (shortcut && shortcut.hotkey === '') {
            return prev.filter((s) => s.id !== id)
          }
          return prev
        })
      }
      this.editingId.set(null)
    },
    onClear: () => {
      const id = this.editingId()
      if (id) {
        this.shortcuts.update((prev) =>
          prev.map((s) =>
            s.id === id
              ? {
                  ...s,
                  hotkey: '' as Hotkey | '',
                  name: this.draftName(),
                  description: this.draftDescription(),
                }
              : s,
          ),
        )
        this.editingId.set(null)
      }
    },
  })

  readonly isRecording = this.recorder.isRecording

  readonly registrations = injectHotkeyRegistrations()

  constructor() {
    // Register all shortcuts dynamically with meta
    injectHotkeys(() =>
      this.shortcuts()
        .filter((s) => s.hotkey !== '')
        .map(
          (s): InjectHotkeyDefinition => ({
            hotkey: s.hotkey as Hotkey,
            callback: () => {
              console.log(`${s.name} triggered:`, s.hotkey)
            },
            options: {
              enabled: !this.recorder.isRecording(),
              meta: {
                name: s.name,
                description: s.description,
              },
            },
          }),
        ),
    )
  }

  handleEdit(id: string): void {
    const shortcut = this.shortcuts().find((s) => s.id === id)
    if (!shortcut) return
    this.editingId.set(id)
    this.draftName.set(shortcut.name)
    this.draftDescription.set(shortcut.description)
    this.recorder.startRecording()
  }

  handleSaveEditing(): void {
    const id = this.editingId()
    if (id) {
      this.shortcuts.update((prev) =>
        prev.map((s) =>
          s.id === id
            ? {
                ...s,
                name: this.draftName(),
                description: this.draftDescription(),
              }
            : s,
        ),
      )
      this.recorder.stopRecording()
      this.editingId.set(null)
    }
  }

  handleCancel(): void {
    this.recorder.cancelRecording()
  }

  handleDelete(id: string): void {
    this.shortcuts.update((prev) => prev.filter((s) => s.id !== id))
  }

  handleCreateNew(): void {
    const newShortcut: Shortcut = {
      id: createId(),
      name: '',
      description: '',
      hotkey: '',
    }
    this.shortcuts.update((prev) => [...prev, newShortcut])
    this.editingId.set(newShortcut.id)
    this.draftName.set('')
    this.draftDescription.set('')
    this.recorder.startRecording()
  }

  onDraftNameInput(event: Event): void {
    this.draftName.set((event.target as HTMLInputElement).value)
  }

  onDraftDescriptionInput(event: Event): void {
    this.draftDescription.set((event.target as HTMLInputElement).value)
  }
}

<div class="app">
  <header>
    <h1>Keyboard Shortcuts Settings</h1>
    <p>
      Customize your keyboard shortcuts. Click "Edit" to record a new shortcut,
      or press Escape to cancel.
    </p>
  </header>

  <main>
    <section class="demo-section">
      <h2>Shortcuts</h2>
      <div class="shortcuts-list">
        @for (shortcut of shortcuts(); track shortcut.id) {
          <div
            class="shortcut-item"
            [class.recording]="editingId() === shortcut.id"
          >
            <div class="shortcut-item-content">
              <div class="shortcut-action">
                @if (editingId() === shortcut.id) {
                  <div class="editing-fields">
                    <input
                      type="text"
                      class="edit-input edit-name"
                      [value]="draftName()"
                      (input)="onDraftNameInput($event)"
                      placeholder="Shortcut name"
                    />
                    <input
                      type="text"
                      class="edit-input edit-description"
                      [value]="draftDescription()"
                      (input)="onDraftDescriptionInput($event)"
                      placeholder="Description (optional)"
                    />
                  </div>
                } @else {
                  @if (shortcut.name) {
                    {{ shortcut.name }}
                  } @else {
                    <span class="unnamed">Unnamed</span>
                  }
                  @if (shortcut.description) {
                    <div class="shortcut-description">
                      {{ shortcut.description }}
                    </div>
                  }
                }
              </div>
              <div class="shortcut-hotkey">
                @if (editingId() === shortcut.id) {
                  <div class="recording-indicator">
                    @if (heldKeys().length > 0) {
                      <div class="held-hotkeys">
                        @for (key of heldKeys(); track key; let i = $index) {
                          @if (i > 0) {
                            <span class="plus">+</span>
                          }
                          <kbd>{{ key }}</kbd>
                        }
                      </div>
                    } @else {
                      <span class="recording-text"
                        >Press any key combination...</span
                      >
                    }
                  </div>
                } @else if (shortcut.hotkey) {
                  <kbd>{{ formatForDisplay(shortcut.hotkey) }}</kbd>
                } @else {
                  <span class="no-shortcut">No shortcut</span>
                }
              </div>
            </div>
            <div class="shortcut-actions">
              @if (editingId() === shortcut.id) {
                <button
                  type="button"
                  class="save-button"
                  (click)="handleSaveEditing()"
                >
                  Save
                </button>
                <button
                  type="button"
                  class="cancel-button"
                  (click)="handleCancel()"
                >
                  Cancel
                </button>
              } @else {
                <button
                  type="button"
                  class="edit-button"
                  (click)="handleEdit(shortcut.id)"
                >
                  Edit
                </button>
                <button
                  type="button"
                  class="delete-button"
                  (click)="handleDelete(shortcut.id)"
                >
                  Delete
                </button>
              }
            </div>
          </div>
        }
      </div>
      <button
        type="button"
        class="create-button"
        (click)="handleCreateNew()"
        [disabled]="isRecording()"
      >
        + Create New Shortcut
      </button>
    </section>

    @if (isRecording()) {
      <div class="info-box recording-notice">
        <strong>Recording shortcut...</strong> Press any key combination or
        Escape to cancel. Press Backspace/Delete to clear the shortcut.
      </div>
    }

    <section class="demo-section">
      <h2>Live Registrations</h2>
      <p>
        This table is powered by
        <code>injectHotkeyRegistrations()</code> — trigger counts, names, and
        descriptions update in real-time as you use your shortcuts.
      </p>
      <table class="registrations-table">
        <thead>
          <tr>
            <th>Hotkey</th>
            <th>Name</th>
            <th>Description</th>
            <th>Enabled</th>
            <th>Triggers</th>
          </tr>
        </thead>
        <tbody>
          @for (reg of registrations.hotkeys(); track reg.id) {
            <tr>
              <td>
                <kbd>{{ formatForDisplay(reg.hotkey) }}</kbd>
              </td>
              <td>{{ reg.options.meta?.name ?? '—' }}</td>
              <td class="description-cell">
                {{ reg.options.meta?.description ?? '—' }}
              </td>
              <td>
                <span
                  [class.status-on]="reg.options.enabled !== false"
                  [class.status-off]="reg.options.enabled === false"
                >
                  {{ reg.options.enabled !== false ? 'yes' : 'no' }}
                </span>
              </td>
              <td class="trigger-count">{{ reg.triggerCount }}</td>
            </tr>
          }
          @if (registrations.hotkeys().length === 0) {
            <tr>
              <td colspan="5" class="empty-row">No hotkeys registered</td>
            </tr>
          }
        </tbody>
      </table>
    </section>

    <section class="demo-section">
      <h2>Usage</h2>
      <pre class="code-block">
import {{
          '{'
        }} injectHotkeys, injectHotkeyRecorder, injectHotkeyRegistrations {{
          '}'
        }} from '&#64;tanstack/angular-hotkeys'

// Register shortcuts dynamically with meta
injectHotkeys(() =>
  this.shortcuts()
    .filter((s) => s.hotkey !== '')
    .map((s) => ({{ '{' }}
      hotkey: s.hotkey,
      callback: () => handleAction(s.id),
      options: {{ '{' }}
        enabled: !this.recorder.isRecording(),
        meta: {{ '{' }} name: s.name, description: s.description {{ '}' }},
      {{ '}' }},
    {{ '}' }})),
)

// Read all registrations reactively
const registrations = injectHotkeyRegistrations()
// registrations.hotkeys()[0].options.meta?.name → 'Save'
// registrations.hotkeys()[0].triggerCount → 3</pre
      >
    </section>
  </main>
</div>

// examples/svelte/create-hotkey-recorder/src/App.svelte
<script lang="ts">
  import {
    createHotkeys,
    createHotkeyRecorder,
    formatForDisplay,
    getHotkeyRegistrations,
  } from '@tanstack/svelte-hotkeys'
  import type { Hotkey } from '@tanstack/svelte-hotkeys'
  import ShortcutListItem from './ShortcutListItem.svelte'

  interface Shortcut {
    id: string
    name: string
    description: string
    hotkey: Hotkey | ''
  }

  let nextId = 0
  function createId(): string {
    return `shortcut_${++nextId}`
  }

  let shortcuts = $state<Array<Shortcut>>([
    {
      id: createId(),
      name: 'Save',
      description: 'Save the current document',
      hotkey: 'Mod+K',
    },
    {
      id: createId(),
      name: 'Open',
      description: 'Open a file from disk',
      hotkey: 'Mod+E',
    },
    {
      id: createId(),
      name: 'New',
      description: 'Create a new document',
      hotkey: 'Mod+G',
    },
    {
      id: createId(),
      name: 'Close',
      description: 'Close the current tab',
      hotkey: 'Mod+Shift+K',
    },
    {
      id: createId(),
      name: 'Undo',
      description: 'Undo the last action',
      hotkey: 'Mod+Shift+E',
    },
    {
      id: createId(),
      name: 'Redo',
      description: 'Redo the last undone action',
      hotkey: 'Mod+Shift+G',
    },
  ])

  let editingId = $state<string | null>(null)
  let draftName = $state('')
  let draftDescription = $state('')

  const recorder = createHotkeyRecorder({
    onRecord: (hotkey: Hotkey) => {
      if (editingId) {
        shortcuts = shortcuts.map((s) =>
          s.id === editingId
            ? { ...s, hotkey, name: draftName, description: draftDescription }
            : s,
        )
        editingId = null
      }
    },
    onCancel: () => {
      if (editingId) {
        const shortcut = shortcuts.find((s) => s.id === editingId)
        if (shortcut && shortcut.hotkey === '') {
          shortcuts = shortcuts.filter((s) => s.id !== editingId)
        }
      }
      editingId = null
    },
    onClear: () => {
      if (editingId) {
        shortcuts = shortcuts.map((s) =>
          s.id === editingId
            ? {
                ...s,
                hotkey: '' as Hotkey | '',
                name: draftName,
                description: draftDescription,
              }
            : s,
        )
        editingId = null
      }
    },
  })

  let isRecording = $derived(recorder.isRecording)

  // Register all shortcuts with meta
  createHotkeys(() =>
    shortcuts
      .filter((s) => s.hotkey !== '')
      .map((s) => ({
        hotkey: s.hotkey as Hotkey,
        callback: () => {
          console.log(`${s.name} triggered:`, s.hotkey)
        },
        options: {
          enabled: !isRecording,
          meta: {
            name: s.name,
            description: s.description,
          },
        },
      })),
  )

  function handleEdit(id: string) {
    const shortcut = shortcuts.find((s) => s.id === id)
    if (!shortcut) return
    editingId = id
    draftName = shortcut.name
    draftDescription = shortcut.description
    recorder.startRecording()
  }

  function handleSaveEditing() {
    if (editingId) {
      shortcuts = shortcuts.map((s) =>
        s.id === editingId
          ? { ...s, name: draftName, description: draftDescription }
          : s,
      )
      recorder.stopRecording()
      editingId = null
    }
  }

  function handleCancel() {
    recorder.cancelRecording()
  }

  function handleDelete(id: string) {
    shortcuts = shortcuts.filter((s) => s.id !== id)
  }

  function handleCreateNew() {
    const newShortcut: Shortcut = {
      id: createId(),
      name: '',
      description: '',
      hotkey: '',
    }
    shortcuts = [...shortcuts, newShortcut]
    editingId = newShortcut.id
    draftName = ''
    draftDescription = ''
    recorder.startRecording()
  }

  // Registrations viewer
  const registrations = getHotkeyRegistrations()
</script>

<div class="app">
  <header>
    <h1>Keyboard Shortcuts Settings</h1>
    <p>
      Customize your keyboard shortcuts. Click "Edit" to record a new shortcut,
      or press Escape to cancel.
    </p>
  </header>

  <main>
    <section class="demo-section">
      <h2>Shortcuts</h2>
      <div class="shortcuts-list">
        {#each shortcuts as shortcut (shortcut.id)}
          <ShortcutListItem
            {shortcut}
            isEditing={editingId === shortcut.id}
            draftName={editingId === shortcut.id ? draftName : shortcut.name}
            draftDescription={editingId === shortcut.id
              ? draftDescription
              : shortcut.description}
            onDraftNameChange={(v) => (draftName = v)}
            onDraftDescriptionChange={(v) => (draftDescription = v)}
            onEdit={() => handleEdit(shortcut.id)}
            onSave={handleSaveEditing}
            onCancel={handleCancel}
            onDelete={() => handleDelete(shortcut.id)}
          />
        {/each}
      </div>
      <button
        type="button"
        class="create-button"
        onclick={handleCreateNew}
        disabled={isRecording}
      >
        + Create New Shortcut
      </button>
    </section>

    {#if recorder.isRecording}
      <div class="info-box recording-notice">
        <strong>Recording shortcut...</strong> Press any key combination or Escape
        to cancel. Press Backspace/Delete to clear the shortcut.
      </div>
    {/if}

    <!-- Registrations Viewer -->
    <section class="demo-section">
      <h2>Live Registrations</h2>
      <p>
        This table is powered by <code>getHotkeyRegistrations()</code> — trigger counts,
        names, and descriptions update in real-time as you use your shortcuts.
      </p>
      <table class="registrations-table">
        <thead>
          <tr>
            <th>Hotkey</th>
            <th>Name</th>
            <th>Description</th>
            <th>Enabled</th>
            <th>Triggers</th>
          </tr>
        </thead>
        <tbody>
          {#each registrations.hotkeys as reg (reg.id)}
            <tr>
              <td>
                <kbd>{formatForDisplay(reg.hotkey)}</kbd>
              </td>
              <td>{reg.options.meta?.name ?? '—'}</td>
              <td class="description-cell">
                {reg.options.meta?.description ?? '—'}
              </td>
              <td>
                <span
                  class={reg.options.enabled !== false
                    ? 'status-on'
                    : 'status-off'}
                >
                  {reg.options.enabled !== false ? 'yes' : 'no'}
                </span>
              </td>
              <td class="trigger-count">{reg.triggerCount}</td>
            </tr>
          {/each}
          {#if registrations.hotkeys.length === 0}
            <tr>
              <td colspan="5" class="empty-row">No hotkeys registered</td>
            </tr>
          {/if}
        </tbody>
      </table>
    </section>

    <section class="demo-section">
      <h2>Usage</h2>
      <pre class="code-block">{`import {
  createHotkeys,
  createHotkeyRecorder,
  getHotkeyRegistrations,
} from '@tanstack/svelte-hotkeys'

// Register shortcuts dynamically with meta
createHotkeys(() =>
  shortcuts.map((s) => ({
    hotkey: s.hotkey,
    callback: () => handleAction(s.id),
    options: {
      enabled: !isRecording,
      meta: { name: s.name, description: s.description },
    },
  })),
)

// Read all registrations reactively
const registrations = getHotkeyRegistrations()
// registrations.hotkeys[0].options.meta?.name → 'Save'
// registrations.hotkeys[0].triggerCount → 3`}</pre>
    </section>
  </main>
</div>
